services:
  osrm:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - OSRM_MAX_MEMORY=8192
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    shm_size: '2gb'
    tmpfs:
      - /tmp:size=2G
    command: >
      /bin/bash -c "
      if [ ! -f '/data/philippines-latest.osrm' ]; then
        echo 'Processing Philippines map data...';
        osrm-extract /data/philippines-latest.osm.pbf -p /opt/car.lua;
        osrm-partition /data/philippines-latest.osrm;
        osrm-customize /data/philippines-latest.osrm;
      else
        echo 'OSRM data already processed, skipping...';
      fi;
      exec osrm-routed --algorithm mld --ip 0.0.0.0 --port 5000 --max-table-size 1000 /data/philippines-latest.osrm"